@startuml
left to right direction

actor "Розробник ПЗ" as Developer
actor "Користувач CLI / Дослідник" as CLIUser

package "Криптографічне ядро (Бібліотека)" {
    (Інтегрувати шифр у застосунок) as UC_Integrate
    (Зашифрувати блоки даних\n/crypto.Block/) as UC_SymEnc
    (Дешифрувати дані приватним ключем\n/crypto.Decrypter/) as UC_AsymDec
    (Запустити автоматизовані бенчмарки) as UC_Bench
}

package "Консольний інтерфейс (CLI)" {
    (Згенерувати асиметричну пару ключів) as UC_GenKeys
    (Зашифрувати файл публічним ключем) as UC_FileEnc
    (Дешифрувати файл приватним ключем) as UC_FileDec
    (Протестувати лавинний ефект\nта аудит дифузії) as UC_Avalanche
}

Developer --> UC_Integrate
Developer --> UC_SymEnc
Developer --> UC_AsymDec
Developer --> UC_Bench

CLIUser --> UC_GenKeys
CLIUser --> UC_FileEnc
CLIUser --> UC_FileDec
CLIUser --> UC_Avalanche
@enduml
